@0xcefb0169decdaccb;  # unique file ID, generated by `capnp id`

using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("vpp_msg");

using import "pose.capnp".Point;

struct Pointcloud {
  points @0 :List(Point);
}
